### ISSUE TITLE
 Template MiningCoinFarm not showing on Flight Sheets #1020 

### ISSUE THREAD

**Issue by raptoreumonline** [minershive/hive-pooltemplates#1027]
Hello ,
as you can see, I'm trying to set up a MiningCoinFarm Template for easy to use BUTK with Flight Sheets
last PR#1020 seems to be clean, but when I log in to the dashboard, it seems that MiningCoinFarm is not yet available
when choosing a pool section !!!!!

Can you advise me where the error is ??
Or why the pool has not yet been added to the Pool section

**Comment by HaloGenius** [comment]
Your pool template works like it should
![servers](https://user-images.githubusercontent.com/11334605/152757369-fd638fd3-2ed3-435e-9617-6053cc3b0de2.png)

Possible it was cause due browser cache in this case logout/login or reload page "Flight Sheets" helps.
