### ISSUE TITLE
Fix template for t-rex on crazypool

### ISSUE THREAD

**Issue by bernaction** [minershive/hive-pooltemplates#1058]
When selecting Crazypool and the T-Rex miner, the POOL URL field is blank.
The template for the fix would be to use:
TCP = **stratum2+tcp://%URL%**
SSL = **stratum2+ssl://%URL%**

For using SSL, add in the template on Extra config arguments: **"no-strict-ssl": true**

**Comment by leofrancia** [comment]
Please very important!

**Comment by koalahbh** [comment]
Hey Devs pls take a look at this asap. Tks
