### ISSUE TITLE
How long before new template is visible

### ISSUE THREAD

**Issue by BKdilse** [minershive/hive-pooltemplates#218]
I created a new config for GNTL, cannot see it under Pool (in the farm config).

Is there something I need to do, or wait for an update?

**Comment by dimafern** [comment]
Synced every hour.

**Comment by BKdilse** [comment]
It's been 2 days.

**Comment by BKdilse** [comment]
Still nothing, is there an issue with my config???

**Comment by HaloGenius** [comment]
Config contains errors so not synced 
Now fixing

**Comment by BKdilse** [comment]
Thanks @HaloGenius, please let me know where I went wrong, so I can avoid this in future.

**Comment by HaloGenius** [comment]
Fixed after aprox ~20 min will be visible in Hive coins presets

**Comment by HaloGenius** [comment]
> 
> 
> Thanks @HaloGenius, please let me know where I went wrong, so I can avoid this in future.
> 
> EDIT: Just spotted, it, website name has duplicate co.uk. Let me know if you want me to correct it?

It was simply bad symbol which broke JSON

**Comment by BKdilse** [comment]
Thanks for that.  I've also now corrected the site names, which had .co.uk duplicated, fixed in #223

**Comment by HaloGenius** [comment]
np
At near future we will planned to introduce some additional feature for pool owners
