### ISSUE TITLE
CrazyPool

### ISSUE THREAD

**Issue by crazypool2019** [minershive/hive-pooltemplates#480]
Hi, 

CrazyPool.org is not showing up

![image](https://user-images.githubusercontent.com/45013538/63784544-cff72c00-c8bc-11e9-9986-4b68dd652abb.png)

![image](https://user-images.githubusercontent.com/45013538/63784599-e69d8300-c8bc-11e9-92dd-d02306ac0fe8.png)

**Comment by HaloGenius** [comment]
If pool not shown after merge then check JSON syntax
We don't provide syntax checking yet
