### ISSUE TITLE
MRR coin template not showing up

### ISSUE THREAD

**Issue by nicklittle430** [minershive/hive-pooltemplates#72]
MRR-Ethash, Lyra2z, Equihash, 192, 144, none of these are showing up in the coins tab. I see some of the other pools and things that were merged just recently, is there some formatting error with the MRR coins, I see other coins that have a hyphen, ie: Nicehash-lyra2z... any insight would be appreciated.

**Comment by minershive** [comment]
Try now

**Comment by nicklittle430** [comment]
There it is! thanks!
