### ISSUE TITLE
Template for lolminer

### ISSUE THREAD

**Issue by rewrewby** [minershive/hive-pooltemplates#87]
Please provide template example for lolMiner and which version do you have?

**Comment by HaloGenius** [comment]
currently we support only very old lolminer version for MNX

**Comment by rewrewby** [comment]
It's time to update to new 0.43b version: https://bitcointalk.org/index.php?topic=4724735.0
There is many AMD cards right now and miners want to mine coins on Equihash 144,5 algo.
