### ISSUE TITLE
Template RaptoreumOnline not showing on Flight Sheets

### ISSUE THREAD

**Issue by raptoreumonline** [minershive/hive-pooltemplates#971]
Hello ,
as you can see, I'm trying to set up a [RaptoreumOnline](https://raptoreum.online) Template for easy to use RTM with Flight Sheets
last PR[#965](https://github.com/minershive/hive-pooltemplates/pull/965) seems to be clean, but when I log in to the dashboard, it seems that RaptoreumOnline is not yet available
when choosing a pool section !!!!!

Can you advise me where the error is ??
Or why the pool has not yet been added to the Pool section

**Comment by HaloGenius** [comment]
We're sorry it was a bug on our side and it's fixed now.

**Comment by raptoreumonline** [comment]
Thank you very much...
