### ISSUE TITLE
miningrigrentals error

### ISSUE THREAD

**Issue by nicklittle430** [minershive/hive-pooltemplates#98]
Miningrigrentals.json is not populating any pools to choose from anymore. Coin is added fine, i.e. MRR-Equihash_144_5 etc. but MRR servers do not show up in the pool template. 

Also, MRR-Equihash_144_5 is displaying in the statistics as Equihash when it should be displayed as Equihash 144_5.

**Comment by minershive** [comment]
because you have ruined the file.
please validate syntax next time

**Comment by nicklittle430** [comment]
How can i correct the syntax for MRR-Equihash_144_5 coin, it is in the equihash 144/5 section in algos. and ewbf is configured to use zhash fork.... 

I will double check the syntax, but all i did was remove the "extra config" section from claymore..

**Comment by nicklittle430** [comment]
I see it already got fixed, thanks.
